# Generated by Django 2.2.8 on 2020-01-03 20:09

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0088_powerfeed_available_power'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consoleport',
            options={'ordering': ('device', django.db.models.functions.text.Length('name'), 'name')},
        ),
        migrations.AlterModelOptions(
            name='consoleporttemplate',
            options={'ordering': ('device_type', django.db.models.functions.text.Length('name'), 'name')},
        ),
        migrations.AlterModelOptions(
            name='consoleserverport',
            options={'ordering': ('device', django.db.models.functions.text.Length('name'), 'name')},
        ),
        migrations.AlterModelOptions(
            name='consoleserverporttemplate',
            options={'ordering': ('device_type', django.db.models.functions.text.Length('name'), 'name')},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': (django.db.models.functions.text.Length('name'), 'name'), 'permissions': (('napalm_read', 'Read-only access to devices via NAPALM'), ('napalm_write', 'Read/write access to devices via NAPALM'))},
        ),
        migrations.AlterModelOptions(
            name='devicebay',
            options={'ordering': ('device', django.db.models.functions.text.Length('name'), 'name')},
        ),
        migrations.AlterModelOptions(
            name='devicebaytemplate',
            options={'ordering': ('device_type', django.db.models.functions.text.Length('name'), 'name')},
        ),
        migrations.AlterModelOptions(
            name='frontport',
            options={'ordering': ('device', django.db.models.functions.text.Length('name'), 'name')},
        ),
        migrations.AlterModelOptions(
            name='frontporttemplate',
            options={'ordering': ('device_type', django.db.models.functions.text.Length('name'), 'name')},
        ),
        migrations.AlterModelOptions(
            name='poweroutlet',
            options={'ordering': ('device', django.db.models.functions.text.Length('name'), 'name')},
        ),
        migrations.AlterModelOptions(
            name='poweroutlettemplate',
            options={'ordering': ('device_type', django.db.models.functions.text.Length('name'), 'name')},
        ),
        migrations.AlterModelOptions(
            name='powerport',
            options={'ordering': ('device', django.db.models.functions.text.Length('name'), 'name')},
        ),
        migrations.AlterModelOptions(
            name='powerporttemplate',
            options={'ordering': ('device_type', django.db.models.functions.text.Length('name'), 'name')},
        ),
        migrations.AlterModelOptions(
            name='rack',
            options={'ordering': ('site', 'group', django.db.models.functions.text.Length('name'), 'name')},
        ),
        migrations.AlterModelOptions(
            name='rearport',
            options={'ordering': ('device', django.db.models.functions.text.Length('name'), 'name')},
        ),
        migrations.AlterModelOptions(
            name='rearporttemplate',
            options={'ordering': ('device_type', django.db.models.functions.text.Length('name'), 'name')},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': (django.db.models.functions.text.Length('name'), 'name')},
        ),
    ]
